apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: 9200
    targetPort: 9200

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
        env:
        - name: discovery.type
          value: single-node
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "1Gi"
        volumeMounts:
        - name: elasticsearch
          mountPath: /usr/share/elasticsearch/data
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
      volumes:
      - name: elasticsearch
        persistentVolumeClaim:
          claimName: elasticsearch-data