apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
      app: db
  ports:
    - protocol: TCP
      port: 3306

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "200Mi"
  volumeMode: Filesystem

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql:8.0
        resources: {}
        env:
          - name: MYSQL_ROOT_HOST
            value: "%"
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: canasta-env
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            value: "mediawiki"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: initdb-volume
          mountPath: /docker-entrypoint-initdb.d
        - name: my-cnf-config
          mountPath: /etc/my.cnf
          subPath: my.cnf
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: initdb-volume
        hostPath:
          path: /canasta/config-data/_initdb
          type: DirectoryOrCreate
      - name: my-cnf-config
        configMap:
          name: canasta-config
          items:
          - key: "my.cnf"
            path: "my.cnf"
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data