apiVersion: batch/v1
kind: Job
metadata:
  name: init
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: init
        image: debian
        command:
        - "bash"
        - "-c"
        - "apt update && apt install git -y && cd /canasta && rm -rf config-data && mkdir config-data && cd config-data && git clone https://github.com/CanastaWiki/Canasta-DockerCompose.git ."
        volumeMounts:
        - name: config-volume
          mountPath: /canasta
      restartPolicy: Never
      volumes:
      - name: config-volume
        hostPath:
          path: /canasta
          type: DirectoryOrCreate