apiVersion: v1
kind: Service
metadata:
  name: varnish
spec:
  selector:
      app: varnish
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
spec:
  selector:
    matchLabels:
      app: varnish
  replicas: 1
  template:
    metadata:
      labels:
        app: varnish
    spec:
      containers:
      - name: varnish
        image: varnish:7.0.2-alpine
        resources:
          limits: {}
        ports:
        - containerPort: 80
        volumeMounts:
          - name: default-vcl-config
            mountPath: /etc/varnish/default.vcl
      volumes:
          - name: default-vcl-config
            hostPath:
              path: /canasta/config-data/config/default.vcl
              type: File